PROJECT="project"
DEV_DIR="devel"
DEV_URL="devel"
NOW=`date +'%Y-%m-%d.%H:%M'`
TMP_DIR="/tmp/new-site"
OLD_DIR="/tmp/old-site"
PROD_DIR="public"

all: $(TARGETS)

dev: all
	@echo "*** Beginning dev build of ${PROJECT} at $(NOW)"
	hugo --baseUrl=${DEV_URL} --buildDrafts=false --buildFuture=false --destination=${DEV_DIR} --disableRSS=true --disableSitemap=true --watch

prod: all
	@echo "*** Beginning prod deploy of ${PROJECT} at $(NOW)"
	if [ ! -d ${PROD_DIR} ]; then mkdir ${PROD_DIR}; fi
	hugo --verbose -d ${TMP_DIR}
	mv ${PROD_DIR} "${OLD_DIR}-${NOW}"
	mv -f ${TMP_DIR} ${PROD_DIR}

clean: all
	@echo "*** Cleaning directories: ${DEV_DIR} ${OLD_DIR}*"
	rm -rf ${DEV_DIR}
	rm -rf ${TMP_DIR}
	rm -rf ${OLD_DIR}*
