#!/bin/bash

set -e

site-usage(){
    cat <<EOM
Usage: site <command>
Commands:
  devl		builds the site and runs a server for live development
  test		builds and deploys the site to the test directory
  prod		builds and deploys the site to the prod directory
  page [name]	creates a new page as: content/name.markdown
  post [name]	creates a new post as: content/post/YYYY-MM-DD-name.markdown
For more help, check the docs: https://github.com/philcryer/fak3r.com
EOM
}

site-devl(){
	site-mess " devl: running server for live devl"
	hugo --verbose server
}

site-post(){
	site-mess " post: upcoming functionality"
	#hugo new [path] [flags]
	#  hugo new [command]
	#  Available Commands:
	#    site        Create a new site (skeleton)
	#      theme       Create a new theme
#
#	      Flags:
#	        -f, --format="toml"
	#touch content/post/`date +'%Y-%m-%d-'`$1
	exit 0
}

site-page(){
	site-mess " page: upcoming functionality"
	exit 0
}

site-test(){ 
	if [ ! -d '$test_dir' ]; then
		mkdir -p $test_dir
	fi
	site-mess " test: building site and deploying to $green$test_dir$reset at $cyan$test_url$reset"
	rm -rf $test_dir/*
	hugo --verbose -b $test_url -d $test_dir
}

site-prod(){ 
	site-mess " prod: building new site to $green/tmp/site-new$reset"
	if [ ! -d '/tmp/site-new' ]; then
		rm -rf /tmp/site-new
	fi
	hugo --verbose -d /tmp/site-new
	now=`date +'%Y-%m-%d.%H:%M'`
	site-mess " prod: backing up existing site to $green$prod_dir-$now$reset"
	sudo mv -f $prod_dir $prod_dir-$now
	site-mess " prod: writing new site to $green$prod_dir$reset"
	sudo mv /tmp/site-new $prod_dir
}

red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
blue=$(tput setaf 4)
purple=$(tput setaf 5)
cyan=$(tput setaf 6)
white=$(tput setaf 7)
reset=$(tput sgr0)

site-mess(){
    msg="$1"
    shift
    pref="++++"
    if [[ $1 ]]; then
        pref="${1:0:4}"
        shift
    fi
    echo "${yellow}[ $cyan$pref$yellow ]$reset  $msg"
}

site-erro(){
    msg="$1"
    shift
    pref="ERRO"
    if [[ $1 ]]; then
        pref="${1:0:4}"
        shift
    fi
    echo "${yellow}[ $red$pref$yellow ]$reset  $msg"
}

if [ ! -f 'site.conf' ]; then
	site-erro "ERROR cannot find site.conf, copy site.conf.example to site.conf and edit"
	exit 1
fi
source site.conf

case $1 in
    devl)
	site-devl
        ;;

    post)
	site-post
        ;;

    prod)
	site-prod
        ;;

    test)
	site-test
        ;;

    *)
	site-usage
        exit 1
        ;;

esac

exit 0
