#!/bin/bash

if [ $# -eq 0 ]; then
  >&2 echo "No arguments provided"
  exit 1
fi

cp $1 src/content/blog/

echo
echo "NEW ---------------------------------------------------------------------------+"
ls -1 src/content/blog/

exit 0

#!/bin/bash

year=2024

rm -rf src/content/blog/*

echo "OLD ---------------------------------------------------------------------------+"
ls -1 ../fak3r.com-master/content/post/$year-*

echo
echo "DONE --------------------------------------------------------------------------+"
ls -1 src/content/blog-done/ | grep $year

exit 0
