#!/bin/bash

year=2023

rm -rf src/content/blog/*

echo
echo "OLD ---------------------------------------------------------------------------+"
ls -1 ../fak3r.com-master/content/post/$year-*

echo
echo "DONE --------------------------------------------------------------------------+"
ls -1 blog-done/ | grep $year

exit 0
