#!/bin/bash

year=2014

if [ ! -d 'src/content/blog' ]; then
  mkdir -p src/content/blog
fi

rm -rf src/content/blog/*
cp ../fak3r.com-main/content/post/$year-* .
cp $year* src/content/blog
ls -ls src/content/blog/*

exit 0

echo
echo "OLD ---------------------------------------------------------------------------+"
ls -1 ../fak3r.com-master/content/post/$year-*

echo
echo "DONE --------------------------------------------------------------------------+"
ls -1 blog-done/ | grep $year

exit 0
