baseurl = "https://fak3r.com"
languageCode = "en-us"
title = "fak3r"
theme = "lithium"
disableKinds = ["taxonomy", "taxonomyTerm", "section", "404"]

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "Search"
    url = "/search/"
[[menu.main]]
    name = "Music"
    url = "/music/"
[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Contact"
    url = "/contact/"

[params]
    description = "slower traffic keep right"
    favicon = "favicon.ico"

[params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

[params.icon]
    url = "logo.png"

[markup.goldmark.renderer]
    unsafe = true
